sharer:
  ip: 127.0.0.1
  port: 7002
  webport: 7003
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  redis:
    blockWhenExhausted: true
    database: 0
    host: 192.168.33.129
    maxIdle: 100
    maxTotal: 2000
    maxWaitMillis: 60000
    minEvictableIdleTimeMillis: 1800000
    numTestsPerEvictionRun: 1024
    #password: 123456
    port: 6379
    softMinEvictableIdleTimeMillis: 10000
    testOnBorrow: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    connTimeout: 6000
    readTimeout: 6000
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #设置空如何序列化
    default-property-inclusion: non_null
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
zookeeper:
  connect:
    url: localhost:2181
    sessionTimeout: 600000
#logging:
#  config: classpath:logback-spring.xml