sharer:
  ip: 127.0.0.1
  port: 7002
  webport: 7003
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  redis:
    blockWhenExhausted: true
    database: 0
    host: 192.168.33.128
    maxIdle: 100
    maxTotal: 2000
    maxWaitMillis: 60000
    minEvictableIdleTimeMillis: 1800000
    numTestsPerEvictionRun: 1024
    password: 123456
    port: 6379
    softMinEvictableIdleTimeMillis: 10000
    testOnBorrow: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    connTimeout: 6000
    readTimeout: 6000
zookeeper:
  connect:
    url: localhost:2181
    sessionTimeout: 600000
#logging:
#  config: classpath:logback-spring.xml